exports.CategoryEnum = {
  CAR: "car",
  REALSTATE: "real estate",
  BIKE: "bike",
  OTHERVEHICLE: "other vehicle",
  ELECTRONICS: "electronics & appliances",
  FURNITURE: "furniture",
  MOBILEGADGET: "mobile & gadgets",
};
exports.SubcategoryEnum = {
  CAR: "car",
  REALSTATERENT: "for rent: house & appartments",
  REALSTATESALE: "for sale: house & appartments",
  PLOT: "plot",
  LAND: "land",
  OTHER: "others",
  MOTORCYCLE: "motorcycle",
  SCOOTER: "scooters",
  BYCYCLE: "bicycle",
  KIDSVEHICLE: "kids vehicles",
  LAPTOP: "laptops & desktops",
  COMPUTERACCESSORIES: "computer accessories",
  TVSPEAKERS: "tv & speakers",
  AC: "ac",
  FRIDGE: "fridges",
  WASHINGMACHINE: "washing machines",
  camera: "cameras",
  OTHERAPPLIANCE: "other appliances",
  SOFA: "sofa & dinning",
  CHAIR: "chairs",
  BED: "bed & wardrobes",
  HOMEDECOR: "home decor & garden",
  OTHERHOUSEHOLD: "other household items",
  MOBILE: "mobile",
  WATCH: "watches",
  TABLET: "tablets",
  GAMECONSOLE: "games & consoles",
  ACCESSORY: "accessories",
};
