name: Greqqo-backend-dev CI-CD
on:
  push:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ubuntu
          key:  ${{ secrets.PRIVATE_KEY  }}
          port:  22
          script: |
               cd /home/hello/greqqo/greqqodev
               bash deploy.sh
